# Site settings
title: Joseph Keane
SEOTitle: Joseph's Blog
description: A blog about computer graphics and other nonsense
keyword: "graphics, blog, joseph keane, black-photon"
url: "http://127.0.0.1:4000"      # your host, for absolute URL
baseurl: ""                                         # for example, '/blog' if your blog hosted on 'host/blog'
avatar: "img/header-avatar.png"                     # the avatar showing on the homepage


# GitHub repository (if the site is hosted by GitHub)
repository: Black-Photon
repository_branch: main


# Theme style settings
theme_style:
  highlight:    # "dark" (default), "light"
  alert:        # "flat" (default), "modern"
  post_preview: # "image" (default), "text"
                # display post's featured image on homepage or not


# Markdown enhancements settings
math:
  enable: true    # false (default), true
                  # math rendering for all posts and keynotes
  engine:         # "katex" (default), "mathjax"
                  # only make sense when `math.engine: true`
chart: true       # false (default), true
mermaid: true     # false (default), true
emoji-plus: true  # false (default), true


# CDN settings
cdn:
  source:       # "jsdelivr" (default), "bootcdn", "unpkg", "cdnjs"
  enable:       # false (default), true
                # optimizing asset files via jsDelivr or not


# Publish posts or collection documents with a future date.
future: true

collections:
  experiences:
    order:
      - arm-modelling.md
      - arm-client.md
      - warwick.md
    output: true
  publications:
    output: false
  projects:
    order:
      - metro.md
      - tellas.md
      - aedmun.md
      - jOSeph.md
      - other.md
    output: true
  politics:
    output: true


# SNS settings
sns:
  github_username: Black-Photon
  linkedin_username: joseph-keane-22256a19a
  email_address: website@joseph-keane.slmail.me


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
permalink: pretty
pagination:
  enabled: true
exclude:
  - package.json
  - package-lock.json
  - README.md
  - README-CN.md
  - LICENSE
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
  - /node_modules
anchorjs: true  # if you want to customize anchor. check out `anchor.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN


# Gems
# you have to `bundle config set path 'vendor/bundle' && bundle install` before local preview
plugins:
  - jekyll-paginate-v2
  - jemoji


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    disable: true                  # we use highlight.js for syntax highlighting, so we disable rouge here


# Navigation menu settings
menus:
  - title: Home
    font: fab fa-fort-awesome
    url: /
  - title: About
    font: fas fa-user-astronaut
    url: /about/
  - title: Projects
    font: fas fa-book
    url: /projects/
  - title: Archive
    font: fas fa-archive
    url: /archive/


# Comment settings
comment:
  provider: gitalk # false (default), "disqus", "gitalk", "valine"

  # Disqus settings
  disqus_username: blackphotons

  # Gitalk settings
  # https://github.com/gitalk/gitalk
  gitalk:
    clientID: '22ecd50e87fe42eb760e'
    clientSecret: 'fa9aa83ea2118061e0b69c287af7bdb54253bf91'
    repo: blog-comments
    owner: Black-Photon
    admin: [Black-Photon]

  # Valine settings
  # https://valine.js.org/
  valine:
    appID:
    appKey:


# Analytics settings
analytics:
  # Baidu Analytics
  ba_track_id: 00504d7a0bf51278aa92b36e60e830b5 # [your baidu track id]

  # Google Analytics
  ga_track_id: 'G-ZYM02DSEHS'               # [your google track id]


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Whether or not to enable Hitokoto (the bubble on homepage)
hitokoto: false # default: false
